### ISSUE TITLE
Plus symbol in email address causes issues

### ISSUE THREAD

**Issue by jwilson77** [Katenkka/enthusiast#11]
I discovered an issue where a user submitted an @gmail.com email address using a plus sign, which is valid as a way for gmail users to use aliases.

Trying to edit this user in Enthusiast control panel results in empty inputs and inability to edit.

![2019-06-20 18_00_46-Enthusiast 3 1 ~ Listing Collective Management System](https://user-images.githubusercontent.com/52054208/59890357-60793380-9385-11e9-8caf-21f85be949b7.png)

User was able to be approved from the dashboard, but email failed on approval with error added to error logs:
![2019-06-20 18_01_36-Enthusiast 3 1 ~ Listing Collective Management System](https://user-images.githubusercontent.com/52054208/59890488-f1500f00-9385-11e9-9466-0cec2fe14000.png)

It doesn't affect display or linking of the email address in the members list.

**Comment by Katenkka** [comment]
Hi,

Thanks for reporting the issue. I will take a look at it.

**Comment by harleykin** [comment]
I am also seeing this.  I am unable to delete a spammer to applied to a list and there was a plus in their gmail address as well.

**Comment by Katenkka** [comment]
@jwilson77 @harleykin 
I fixed this issue. Please updated changed files (public/enthusiast/affiliates.php and public/enthusiast/members.php) and confirm that everything's okay

**Comment by jwilson77** [comment]
Appears to be working for me. Thank you!

**Comment by Katenkka** [comment]
Okay, then I will close the issue since the reporter says it's fixed.
Feel free to create a new one in case of other errors.
